/**
 * M-PESA STK Push Implementation
 * 
 * This module handles STK Push requests to Safaricom Daraja API.
 * STK Push sends a payment prompt directly to the customer's phone.
 * 
 * SECURITY:
 * - Password is generated dynamically using shortcode + passkey + timestamp
 * - Amount is always retrieved from database, never from client
 * - Phone numbers are normalized before sending
 * - All sensitive operations happen server-side
 */

import { getMpesaConfig, getStkPushUrl, isMock } from './config';
import { getAccessToken } from './auth';
import { normalizePhoneNumber } from './phone';
import {
  StkPushRequest,
  StkPushResponse,
  PaymentStatus,
} from './types';
import { StkPushFailedError, MpesaNetworkError } from './errors';
import { mockInitiateStkPush } from './mock-stk-push';

/**
 * Generate current timestamp in format YYYYMMDDHHmmss
 * 
 * Daraja requires timestamps in this specific format
 * 
 * @returns Timestamp string
 */
export function generateTimestamp(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  const hours = String(now.getHours()).padStart(2, '0');
  const minutes = String(now.getMinutes()).padStart(2, '0');
  const seconds = String(now.getSeconds()).padStart(2, '0');

  return `${year}${month}${day}${hours}${minutes}${seconds}`;
}

/**
 * Generate STK Push password
 * 
 * Daraja password is generated by Base64 encoding:
 * BusinessShortCode + Passkey + Timestamp
 * 
 * @returns Base64 encoded password
 */
export function generateStkPushPassword(): string {
  const config = getMpesaConfig();
  const timestamp = generateTimestamp();
  const passwordString = `${config.shortcode}${config.passkey}${timestamp}`;
  return Buffer.from(passwordString).toString('base64');
}

/**
 * Initiate STK Push request
 * 
 * This function:
 * 1. Normalizes the phone number
 * 2. Generates dynamic password and timestamp
 * 3. Obtains OAuth access token
 * 4. Sends STK Push request to Daraja
 * 5. Returns the response with payment identifiers
 * 
 * @param amount - Amount in cents (will be converted to KSh)
 * @param phoneNumber - Customer phone number
 * @param accountReference - Order ID or reference
 * @param transactionDesc - Transaction description
 * @returns STK Push response with MerchantRequestID and CheckoutRequestID
 * @throws StkPushFailedError if STK Push fails
 * @throws MpesaNetworkError if network request fails
 */
export async function initiateStkPush(
  amount: number,
  phoneNumber: string,
  accountReference: string,
  transactionDesc: string = 'Jewelry Purchase'
): Promise<StkPushResponse> {
  try {
    const config = getMpesaConfig();
    
    // Use mock implementation in mock mode
    if (isMock()) {
      return await mockInitiateStkPush({
        phoneNumber,
        amount,
        orderId: accountReference,
      });
    }
    
    // Normalize phone number
    const normalizedPhone = normalizePhoneNumber(phoneNumber);
    
    // Convert amount from cents to KSh (Daraja expects KSh, not cents)
    const amountKSh = Math.ceil(amount / 100);
    
    if (amountKSh <= 0) {
      throw new StkPushFailedError('0', 'Amount must be greater than zero');
    }

    // Generate password and timestamp
    const timestamp = generateTimestamp();
    const password = generateStkPushPassword();

    // Get access token
    const accessToken = await getAccessToken();

    // Build STK Push request payload
    const stkPushRequest: StkPushRequest = {
      BusinessShortCode: config.shortcode,
      Password: password,
      Timestamp: timestamp,
      TransactionType: 'CustomerPayBillOnline', // Use 'CustomerBuyGoodsOnline' for Till Number
      Amount: amountKSh,
      PartyA: normalizedPhone, // Phone number sending money (customer)
      PartyB: config.shortcode, // Shortcode receiving money
      PhoneNumber: normalizedPhone, // Phone number to receive STK Push
      CallBackURL: config.callbackUrl,
      AccountReference: accountReference,
      TransactionDesc: transactionDesc,
    };

    // Send STK Push request
    const response = await fetch(getStkPushUrl(), {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(stkPushRequest),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new StkPushFailedError(
        response.status.toString(),
        `STK Push request failed: ${errorText}`
      );
    }

    const data: StkPushResponse = await response.json();

    // Check if STK Push was successful
    // ResponseCode "0" means success
    if (data.ResponseCode !== '0') {
      throw new StkPushFailedError(
        data.ResponseCode,
        data.ResponseDescription || 'STK Push failed'
      );
    }

    return data;
  } catch (error) {
    if (error instanceof StkPushFailedError || error instanceof MpesaNetworkError) {
      throw error;
    }

    if (error instanceof TypeError && error.message.includes('fetch')) {
      throw new MpesaNetworkError('Failed to connect to Daraja STK Push endpoint');
    }

    throw new StkPushFailedError(
      'UNKNOWN',
      `Unexpected error: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}

/**
 * Query STK Push status
 * 
 * This function can be used to check the status of a pending STK Push transaction.
 * However, the callback is the primary method for receiving payment results.
 * 
 * @param checkoutRequestId - Checkout Request ID from STK Push response
 * @returns Query response
 */
export async function queryStkPushStatus(checkoutRequestId: string): Promise<any> {
  try {
    const config = getMpesaConfig();
    const accessToken = await getAccessToken();
    const timestamp = generateTimestamp();
    const password = generateStkPushPassword();

    const queryRequest = {
      BusinessShortCode: config.shortcode,
      Password: password,
      Timestamp: timestamp,
      CheckoutRequestID: checkoutRequestId,
    };

    const response = await fetch(getStkPushUrl().replace('processrequest', 'query'), {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(queryRequest),
    });

    if (!response.ok) {
      throw new Error(`Query failed with status ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    throw new MpesaNetworkError(
      `Failed to query STK Push status: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}
